import onBoarding from "../assets/images/onboarding.png"
import googleIcon from "../assets/images/google.png"
import homeIcon from "../assets/images/home.png"
import groupIcon from "../assets/images/group.png"
import postIcon from "../assets/images/post.png"
import messageIcon from "../assets/images/message.png"
import settingIcon from "../assets/images/settings.png"
import searchIcon from "../assets/images/search.png"
import leftArrawIcon from "../assets/images/left-arrow.png"
import rightArraowIcon from "../assets/images/right-arrow.png"


export const ICONS={
    profile:{
        setting:settingIcon,
        title:"setting"
    },
    backgroundIcons:{
        icon:onBoarding,
        title:"Background Images"
    },
    googleIcons:{
        icon:googleIcon,
        title:"google icon"
    },
    message:{
        icon:searchIcon,
        title:"Search Icon"
    },
    messageScreen:{
            icon:leftArrawIcon,
            title:"go The Message"
    },
    sendMessage:{
        icon:rightArraowIcon,
        title:"send Message"
    },
    homeScreen:{

        home:{
            icon:homeIcon,
            title:"Home Icon"
        },
        group:{
            icon:groupIcon,
            title:"Group Icon"
        },
        post:{
            icon:postIcon,
            title:"Post Icon"
        },
        message:{
            icon:messageIcon,
            title:"Message Icon"

        }

    }
    
}
